
from examplePORIS import *

model = examplePORIS()
sysExample = model.root

print("\n\n\nSys:",sysExample.name)
print("\nmodes:",sysExample.modes)
print("\nselected:",sysExample.selectedMode.name)
'''
print("\n\n\nPhotometry:",mdExamplePhotometry.name)
print("\nsubmodes:",mdExamplePhotometry.submodes)
print("\n\n\nSys:",sysFilter.name)
print("\nmodes:",sysFilter.modes)
print("\nselected:",sysFilter.selectedMode.name)
print("\n\n\nSys:",sysDetector.name)
print("\nmodes:",sysDetector.modes)
print("\nselected:",sysDetector.selectedMode.name)
print("\n\n\nParam:",prClassicFilters.name)
print("\nmodes:",prClassicFilters.modes)
print("\nselected:",prClassicFilters.selectedMode.name)
print("\nvalues:",prClassicFilters.values)
print("\nselected:",prClassicFilters.selectedValue.name)
print("\n\n\nParam:",prDispersion.name)
print("\nmodes:",prDispersion.modes)
print("\nselected:",prDispersion.selectedMode.name)
print("\nvalues:",prDispersion.values)
print("\nselected:",prDispersion.selectedValue.name)
print("\n\n\nParam:",prBinning.name)
print("\nmodes:",prBinning.modes)
print("\nselected:",prBinning.selectedMode.name)
print("\nvalues:",prBinning.values)
print("\nselected:",prBinning.selectedValue.name)
print("\n\n\nParam:",prExpTime.name)
print("\nmodes:",prExpTime.modes)
print("\nselected:",prExpTime.selectedMode.name)
print("\nvalues:",prExpTime.values)
print("\nselected:",prExpTime.selectedValue.name)
print("\n\n\nParam:",prMasks.name)
print("\nmodes:",prMasks.modes)
print("\nselected:",prMasks.selectedMode.name)
print("\nvalues:",prMasks.values)
print("\nselected:",prMasks.selectedValue.name)

print("\n\nSquare binning values:",mdBinningSquare.values)
'''
mdExamplePhotometry = sysExample.getModeFromName("InstrumentMode_Photometry")
print(mdExamplePhotometry)
sysExample.setMode(mdExamplePhotometry)
'''
print("\n\n\nSelected filter:",prClassicFilters.selectedValue.name)
print("\n\n\nSelected dispersion:",prDispersion.selectedValue.name)
print("\n\n\nSelected detector mode:",sysDetector.selectedMode.name)
print("\n\n\nSelected binning mode:",prBinning.selectedMode.name)
'''
prBinning = sysExample.getDescendantParamFromName("Binning")
print("\n\n\nSelected binning:",prBinning.selectedValue.name)
prDispersion = sysExample.getDescendantParamFromName("Dispersion")
print("\n\n\nSelected dispersion:",prDispersion.selectedValue.name)

'''
print("\n\n\nSelected expTime:",prExpTime.selectedValue.name)
print("\n\n\nSelected mask:",prMasks.selectedValue.name)
'''
vlBinning2x2 = prBinning.getValueFromName("Binning_2x2")
prBinning.setValue(vlBinning2x2)
print("\n\n\nSelected binning:",prBinning.selectedValue.name)
print("\n\n\nSelected dispersion:",prDispersion.selectedValue.name)
vlBinning1x2 = prBinning.getValueFromName("Binning_1x2")
prBinning.setValue(vlBinning1x2)
print("\n\n\nSelected binning:",prBinning.selectedValue.name)
print("\n\n\nSelected dispersion:",prDispersion.selectedValue.name)
mdExampleSpectroscopy = sysExample.getModeFromName("InstrumentMode_Spectroscopy")
sysExample.setMode(mdExampleSpectroscopy)
print("\n\n\nSelected binning:",prBinning.selectedValue.name)
print("\n\n\nSelected dispersion:",prDispersion.selectedValue.name)
prBinning.setValue(vlBinning1x2)
print("\n\n\nSelected binning:",prBinning.selectedValue.name)
print("\n\n\nSelected dispersion:",prDispersion.selectedValue.name)
sysExample.setMode(mdExamplePhotometry)
print("\n\n\nSelected binning:",prBinning.selectedValue.name)
print("\n\n\nSelected dispersion:",prDispersion.selectedValue.name)

'''
print("\n\n\nSelected Example mode:",sysExample.selectedMode.name)
print("\n\n\nSpectroscopy submodes:",mdExampleSpectroscopy.submodes)
print("\n\n\nSelected filter:",prClassicFilters.selectedValue.name)
print("\n\n\nSelected dispersion:",prDispersion.selectedValue.name)
print("\n\n\nSelected detector mode:",sysDetector.selectedMode.name)
print("\n\n\nSelected binning mode:",prBinning.selectedMode.name)
print("\n\n\nSelected binning:",prBinning.selectedValue.name)
print("\n\n\nSelected expTime:",prExpTime.selectedValue.name)
print("\n\n\nSelected masks mode:",prMasks.selectedMode.name)
print("\n\n\nSelected mask:",prMasks.selectedValue.name)
prBinning.setValue(vlBinning1x2)
print("\n\n\nSelected Example mode:",sysExample.selectedMode.name)
print("\n\n\nSpectroscopy submodes:",mdExampleSpectroscopy.submodes)
print("\n\n\nSelected filter:",prClassicFilters.selectedValue.name)
print("\n\n\nSelected dispersion:",prDispersion.selectedValue.name)
print("\n\n\nSelected detector mode:",sysDetector.selectedMode.name)
print("\n\n\nSelected binning mode:",prBinning.selectedMode.name)
print("\n\n\nSelected binning:",prBinning.selectedValue.name)
print("\n\n\nSelected expTime:",prExpTime.selectedValue.name)
print("\n\n\nSelected masks mode:",prMasks.selectedMode.name)
print("\n\n\nSelected mask:",prMasks.selectedValue.name)
'''    
